controller_manager:
  ros__parameters:
    use_sim_time: False
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - hand0
      - hand1
      - hand2
      - hand3
      - hand4
      - hand5
      - hand6
      - hand7
      - hand8
      - hand9
      - hand10
      - hand11
      - hand12
      - hand13
      - hand14
      - hand15


    interface_name: position

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity
      - effort

    state_publish_rate: 200.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)

